### ISSUE TITLE
打开分类、标签、关于页面有问题

### ISSUE THREAD

**Issue by wangcongi** [Sariay/hexo-theme-Annie#12]
出现Cannot GET/xxxx

**Comment by Sariay** [comment]
请确保创建了相应的页面，如：

```hexo new page "about"```,  具体见于[Annie主题使用说明](https://sariay.github.io/2018/08/27/Annie%E4%B8%BB%E9%A2%98%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/) **分类页的使用** 等节

@wangcongi
