### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by Ascotbe** [Sariay/hexo-theme-Annie#17]
主题中点加载更多进入下一页后会无限加载，再次点击后会无限重复第二页

**Comment by Sariay** [comment]
@Ascotbe 

！可能代码存在逻辑问题，可以给一下网址链接，我具体看看？

**Comment by Ascotbe** [comment]
> @Ascotbe
> 
> ！可能代码存在逻辑问题，可以给一下网址链接，我具体看看？

https://ascotbe.github.io/

**Comment by Ascotbe** [comment]
> @Ascotbe
> 
> ！可能代码存在逻辑问题，可以给一下网址链接，我具体看看？

还有个问题 网站设置简体后 会自动跳成繁体，不能初始化就是简体字体吗

**Comment by Sariay** [comment]
@Ascotbe 

你好：

关于语言的简繁问题：请将main.js的Annie_WordSet()函数注释掉（相关：功能未完善）

关于加载问题，你似乎调整了leancloud.js中的代码，请去除init(Counter)函数中多余的 **,** 和 **}** 符号  (相关：js的单线程问题)

**Comment by Ascotbe** [comment]
> @Ascotbe
> 
> 你好：
> 
> 关于语言的简繁问题：请将main.js的Annie_WordSet（）函数注释掉（相关：功能未完善）
> 
> 关于加载问题，你似乎调整了leancloud.js中的代码，请去除init（Counter）函数中多余的**，**和**}**符号（相关：js的单线程问题）

感谢大佬，还有个小问题如何把主页的那段话居中呢

**Comment by Sariay** [comment]
@Ascotbe 

定位到文件Annie.css，调整类**header .motto**中的属性**margin: 4em auto;**。

你可以调整上下边距，例如**margin: 8em auto;**，使之看起来垂直方向居中。

至于绝对的垂直居中，你可以对它的父元素使用绝对定位（Google一下教程）

**Comment by Ascotbe** [comment]
> header .motto

万分感谢已成功
