### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by Ascotbe** [Sariay/hexo-theme-Annie#19]
主页文字颜色在哪个位置目前只找到一个导航栏的颜色调节，还有最下面的github，邮箱什么的图标如何更改，如何添加。最后一个问题就是网站点开一篇文章后下面推荐的文章会显示你所有的文章，因为要显示图片所以会导致文章加载很慢，如何解决只显示3-5篇。

**Comment by Sariay** [comment]
@Ascotbe 

01 个人定制化的问题：请Google ！

02 文章篇数的问题: 请仔细阅读《使用说明》（**第十三节**）

03 加载速度的问题：请寻找一个好的图床！

**Comment by Ascotbe** [comment]
指的是这个中在这么添加多的连接,还有对应的图标文件在哪里
social:
    enable: true
    github: http://github.com/
    weibo: http://github.com/
    email: mailto:http://github.com/
    qq: http://github.com/
    twitter: http://github.com/

**Comment by Sariay** [comment]
图标写死了，到footer.ejs中修改 

@Ascotbe

**Comment by Ascotbe** [comment]
> 图标写死了，到footer.ejs中修改 @Ascotbe

关于图标的只有这一句代码，请问如何修改
	<div class="social">
		<%- partial('social') %>
	</div>

**Comment by Sariay** [comment]
@Ascotbe 

social.ejs文件中

**Comment by Ascotbe** [comment]
> @Ascotbe
> 
> social.ejs文件中

好的谢谢，晚上回去试下
