### ISSUE TITLE
随机背景图片I

### ISSUE THREAD

**Issue by Bestyluo** [Sariay/hexo-theme-Annie#2]
hello,您好
   header部分的随机背景图片,一直无法显示, 我应该怎么解决呢?

**Comment by incredibledays** [comment]
我也是

**Comment by Sariay** [comment]
晚好！

方法一：请在 **themes/annie/source/img** 下建立文件夹 **random** ，并在 random 存入图片即可（命名格式为0.jpg  ... 110.jpg）。所需图片可以到另一个仓库里下载 [hexo-theme-Annie的随机图片集](https://github.com/Sariay/Random-img)。

方法二：请注释掉 **main.js**文件里的函数`var Annie_Random = function() {  }；
`

目前主题正在完善，也在备考，请多包涵！


@zaoyifan / @Bestyluo

**Comment by incredibledays** [comment]
@Sariay 问题已解决，感谢

**Comment by Bestyluo** [comment]
谢谢你,问题解决了.

**Comment by SeniorBrother** [comment]
方法1 图片必须放很多才行 我只放十张不起作用
方法2 注释了 函数 图片不显示还是空白

**Comment by Sariay** [comment]
**方法1**

main.js文件中修改下函数：var Annie_Random = function() { }；

109 + 1 表示随机数范围从0到110

9 + 1 表示随机数范围从0.jpg到10.jpg

**方法2**

注释函数后，设置主题目录下的_config.yml文件：enable=true

background_image:

    enable: true

    url: https://source.unsplash.com/collection/954550/1920x1080

（ so sorry，改天修改下接口，在_config.yml文件中配置即可！）


@SeniorBrother

**Comment by frank0123** [comment]
两种当时都尝试过了，还是不能显示图片！我通过 inspect（google浏览器，查看元素）查看发现，我尽管在 public/js/main.js 中注释或修改了函数var Annie_Random = function() { }；，但是在查看的显示里发现并没有改变，还是保持原来的代码逻辑！

**Comment by Sariay** [comment]
下午好!

**public/.../..**  为生成后的库，在这里修改会被覆盖。

**修改路径为：** D:\hexo\themes\annie\source\js。

@frank0123

**Comment by frank0123** [comment]
按照您方法二的指示，我在var Annie_Random = function() { }；函数中做的修改如下：
```
var random_bg = Math.floor(Math.random() * 9 + 1);
var bg = 'url(/img/random/' + random_bg + '.jpg)';
$("header").css("background-image", bg);
```
并且在 themes/annie/source/img 路径下创建了random 文件夹，放入01~10 10张jpg张图片；还是无法显示图片。现在能显示图片的方法，只有 注释掉 函数var Annie_Random = function() { }；，在themes/annie/_config.yml文件中保持 背景图片原来的设置：
```
background_image:
        enable: true
        url: https://source.unsplash.com/collection/954550/1920x1080
```

才可行！我尝试直接使用本地图片路径，即如下：

```
background_image:
        enable: true
        url: img/random/01.jpg

```
也是不行的！不知道我错在哪里了？！

**Comment by Sariay** [comment]
我测试了，可以使用的！

**1 图片命名格式**：0.jpg ... 10.jpg ... 110.jpg

**2 使用本地图片**：此时，请注释函数 var Annie_Random = function() { }


@frank0123

**Comment by frank0123** [comment]
真抱歉，是我把图片的命名格式搞错了！现在可以了！谢谢您了！@Sariay
