### ISSUE TITLE
切换背景怎么使用

### ISSUE THREAD

**Issue by alterem** [Sariay/hexo-theme-Annie#22]
切换背景怎么使用

**Comment by alterem** [comment]
还有一个问题：article-title不能在页面显示出来，现在进入文章想要显示标题

**Comment by alterem** [comment]
页面fixbackground的背景有时候加载不出来 是空白

**Comment by Sariay** [comment]
- 背景切换功能：未实现

- 无法加载背景：网络问题，背景路径问题（遮罩最长10s左右后移除）

@alterem

**Comment by alterem** [comment]
不好意思最近在忙忘了关注issues，
网络背景 控制台报错（Access-Control-Allow-Origin）
Access to image at 'https://images.unsplash.com/photo-1550690638-b9f389eca280?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=680&h=440&q=80' from origin 'https://blog.alterem.top' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.js:117 GET https://images.unsplash.com/photo-1550690638-b9f389eca280?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=680&h=440&q=80 net::ERR_FAILED
