### ISSUE TITLE
网络背景 控制台报错（Access-Control-Allow-Origin）

### ISSUE THREAD

**Issue by alterem** [Sariay/hexo-theme-Annie#23]
不好意思最近在忙忘了关注issues，
网络背景 控制台报错（Access-Control-Allow-Origin）
Access to image at 'https://images.unsplash.com/photo-1550690638-b9f389eca280?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=680&h=440&q=80' from origin 'https://blog.alterem.top' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.js:117 GET https://images.unsplash.com/photo-1550690638-b9f389eca280?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=680&h=440&q=80 net::ERR_FAILED

_Originally posted by @alterem in https://github.com/Sariay/hexo-theme-Annie/issues/22#issuecomment-474164789_

**Comment by Sariay** [comment]
@alterem 

控制台报错（Access-Control-Allow-Origin）：你访问的图片不允许**跨域访问**。

似乎unsplash允许的吧！

（你可以关注main.js文件中Annie_ColorExtraction(img)函数，搜索关键词注释掉！**bug**）

**Comment by alterem** [comment]
还是不能解决这个问题

**Comment by alterem** [comment]
为何不把`
	(function Annie_Init() {
		Annie_Preloader();
		Annie_Nav();
		Annie_Progress();
		Annie_Toc();
		Annie_ToAnchor();
		Annie_Archive();
		Annie_LoadPost();
		Annie_Tab();
		Annie_TCP();
		Annie_WordSet();
	})();`
换成`
	jQuery(function($){
		Annie_Preloader();
		Annie_Nav();
		Annie_Progress();
		Annie_Toc();
		Annie_ToAnchor();
		Annie_Archive();
		Annie_LoadPost();
		Annie_Tab();
		Annie_TCP();
		Annie_WordSet();
		function changeHeaderBg() {
			debugger
		}
	});`
