### ISSUE TITLE
prism 代码没有高亮

### ISSUE THREAD

**Issue by seriouszyx** [Sariay/hexo-theme-Annie#24]
代码没有高亮，这个可以增加高亮的语言吗

![E325AFBE-289E-4C17-857C-C6E378B68962](https://user-images.githubusercontent.com/33992371/55235472-9a480b80-5268-11e9-825d-64444e70f619.png)

**Comment by Sariay** [comment]
额，代码块应该这么写吧！

、、、java


这里是代码


、、、

@seriouszyx

**Comment by seriouszyx** [comment]
> 额，代码块应该这么写吧！
> 
> 、、、java
> 
> 这里是代码
> 
> 、、、
> 
> @seriouszyx

可能是魔改出错了吧
