### ISSUE TITLE
hexo g 生成文件成功，但是打不开页面

### ISSUE THREAD

**Issue by 9yues** [Sariay/hexo-theme-Annie#25]
hexo g 生成文件成功，而且我也启动了
![image](https://user-images.githubusercontent.com/19297519/55314253-58071000-549c-11e9-8912-930e0d59b76a.png)
然后看了下 public  文件夹里的.index.html 居然是空的，这是什么情况
![image](https://user-images.githubusercontent.com/19297519/55314291-6f45fd80-549c-11e9-9be9-a599f6155f69.png)
最后附上我的_config.yml文件截图
![image](https://user-images.githubusercontent.com/19297519/55314317-7bca5600-549c-11e9-92aa-5600efa5a76b.png)

**Comment by jessie975** [comment]
题主怎么解决的呀~我也遇到了这个问题

**Comment by 9yues** [comment]
> 题主怎么解决的呀~我也遇到了这个问题
老实说，我忘了。。。。
