### ISSUE TITLE
代码复制问题

### ISSUE THREAD

**Issue by ab-Alex** [Sariay/hexo-theme-Annie#27]
@Sariay 点击代码复制 会自动跳转到页头 这是怎么回事？

**Comment by Sariay** [comment]
是否可以提供一个涉及该问题的网页(地址)，我需要复现问题！ 

@ab-Alex

**Comment by ab-Alex** [comment]
http://ab-alex.xyz @Sariay

**Comment by ab-Alex** [comment]
@Sariay 不好意思我已经解决啦。
把custom_css弄成空就好啦

**Comment by Sariay** [comment]
看了几个页面，没问题的！ @ab-Alex

**Comment by ab-Alex** [comment]
已解决……
