### ISSUE TITLE
附加功能问题：live2d()

### ISSUE THREAD

**Issue by Palpitation-github** [Sariay/hexo-theme-Annie#29]
大佬您好，我是您主题的老用户，之前修改的live2d萌板娘的 https://github.com/EYHN/hexo-helper-live2d ，现在更新之后也想添加，但是不知道该在哪添加，才可以
还有就是以前的主题有刚加载进主页时，有可以自己设置的图片作为加载动画（我之前设置的是一个gif）现在我还想修改成原来的那种感觉，可以帮帮我嘛，蟹蟹，♥

**Comment by Sariay** [comment]
你这样，我真的很难受！！！

[萌板娘](https://github.com/EYHN/hexo-helper-live2d)项目主页已经介绍了它的使用。

至于自定义加载动画，你可在header.ejs找到相应的代码块，添加自己的代码就行。

@voidmaker69 ，浮川

**Comment by Palpitation-github** [comment]
对对对，我的意思就是是在header.ejs里面修改还是在别处，我怕破坏了某些地方的布局，蟹蟹
