### ISSUE TITLE
文章的封面图怎么设置？

### ISSUE THREAD

**Issue by runzhenghengbin** [Sariay/hexo-theme-Annie#3]
> 现在都是默认设置的，我怎么能修改

**Comment by Sariay** [comment]
哈！

请看 **配置-3** 文章模板样例，其中的 **cover** 即文章封面图。（绝对路径或相对路径）

@runzhenghengbin

**Comment by zhenglianghan** [comment]
别的都蛮好，代码块格式错乱咋整

**Comment by Sariay** [comment]
- 在站点目录下的_config.yml文件中，修改下列部分代码，即关闭hexo自带的代码高亮功能。

**highlight:
       enable: false**
       line_number: true
       auto_detect: false
       tab_replace:

- 今晚会pull，修复代码显示、增加相册模块等，你可以晚些时候**clone**使用

@zhenglianghan

**Comment by zhenglianghan** [comment]
好的好的，辛苦老哥了

**Comment by 520Muzili** [comment]
主页的那些封面大图在哪设置?

**Comment by Sariay** [comment]
午好！

你不妨等更新完毕后，按照文章[《Annie主题使用说明》](https://sariay.github.io/2018/08/27/Annie主题使用说明/)配置即可！

@520Muzili
