### ISSUE TITLE
覆盖了 window.onload 函数问题，导致 tag cloud 函数钩子不执行

### ISSUE THREAD

**Issue by Palpitation-github** [Sariay/hexo-theme-Annie#30]
我在尝试使用 hexo-tag-cloud 的 3D球状标签云的时候，发现无论怎么尝试也无法显示
在 https://dlovexj.cn/tags/ 页面的 console 使用如下代码验证：
try {
        TagCanvas.textFont = 'Trebuchet MS, Helvetica';
        TagCanvas.textColour = '#333';
        TagCanvas.textHeight = 18;
        TagCanvas.outlineColour = '#E2E1C1';
        TagCanvas.maxSpeed = 0.03;
        TagCanvas.outlineMethod = 'block';
        TagCanvas.minBrightness = 0.2;
        TagCanvas.depth = 0.92;
        TagCanvas.pulsateTo = 0.6;
        TagCanvas.initial = [0.1,-0.1];
        TagCanvas.decel = 0.98;
        TagCanvas.reverse = true;
        TagCanvas.hideTags = false;
        TagCanvas.shadow = '#ccf';
        TagCanvas.shadowBlur = 3;
        TagCanvas.weight = false;
        TagCanvas.imageScale = null;
        TagCanvas.fadeIn = 1000;
        TagCanvas.clickToFront = 600;
        TagCanvas.Start('resCanvas');
        TagCanvas.tc['resCanvas'].Wheel(false)
    } catch(e) {
        console.log(e);
        document.getElementById('myCanvasContainer').style.display = 'none';
    }
发现可以显示，3d标签云的插件作者提示 尽量不要暴力直接 window.onload = func() {...}这样之后的不好改写

**Comment by Palpitation-github** [comment]
能把上面那段代码加进主题的 window.onload 函数里呢

**Comment by Sariay** [comment]
@voidmaker69 

解决方法1：main.js文件中新建Annie_TagCloud()函数，并初始化之。

**新建函数**
```
	var Annie_TagCloud = function() {
		try {
			TagCanvas.textFont = 'Trebuchet MS, Helvetica';
			TagCanvas.textColour = '#333';
			TagCanvas.textHeight = 18;
			TagCanvas.outlineColour = '#E2E1C1';
			TagCanvas.maxSpeed = 0.03;
			TagCanvas.outlineMethod = 'block';
			TagCanvas.minBrightness = 0.2;
			TagCanvas.depth = 0.92;
			TagCanvas.pulsateTo = 0.6;
			TagCanvas.initial = [0.1, -0.1];
			TagCanvas.decel = 0.98;
			TagCanvas.reverse = true;
			TagCanvas.hideTags = false;
			TagCanvas.shadow = '#ccf';
			TagCanvas.shadowBlur = 3;
			TagCanvas.weight = false;
			TagCanvas.imageScale = null;
			TagCanvas.fadeIn = 1000;
			TagCanvas.clickToFront = 600;
			TagCanvas.Start('resCanvas');
			TagCanvas.tc['resCanvas'].Wheel(false)
		} catch(e) {
			console.log(e);
			document.getElementById('myCanvasContainer').style.display = 'none';
		}
	};

	/* Other js functions */
	/* ... */
```

**初始化函数**
```
	/* Initialize */
	(function Annie_Init() {
		Annie_Preloader();
		Annie_Nav();
		Annie_Progress();
		Annie_Toc();
		Annie_ToAnchor();
		Annie_Archive();
		Annie_LoadPost();
		Annie_Tab();
		Annie_TCP();
		Annie_WordSet();
		Annie_TagCloud();//初始化
	})();
```

**Comment by Sariay** [comment]
解决方法2：下面两个js文件放在main.js文件后加载
```
<script type="text/javascript" charset="utf-8" src="js/tagcloud.js"></script>
<script type="text/javascript" charset="utf-8" src="js/tagcanvas.js"></script>
```

**两种方法的本质：重新加载执行函数**

**Comment by Palpitation-github** [comment]
蟹蟹，问题已经解决

**Comment by Palpitation-github** [comment]
使用了方法一，不过hexo s本地可以显示，hexo d 线上显示不出来，在等待看是不是没刷新

**Comment by Palpitation-github** [comment]
通过验证发现在本地使用方法一这样可以显示，上线则不可以

**Comment by Palpitation-github** [comment]
好啦，可能是github的问题，现在可以显示啦，非常感谢
