### ISSUE TITLE
博主，我感觉你这个背景图片颜色的rgb提取好像有点问题

### ISSUE THREAD

**Issue by 9yues** [Sariay/hexo-theme-Annie#31]
不管怎么刷新，那个字体依然是白色，仿佛是没有正确的提取到rgb值

**Comment by Sariay** [comment]
额，这个不算bug！你可以看下[vibrant](https://github.com/jariz/vibrant.js)插件。

提取的是图片的主色，根据主色的rgb值计算YUV中Y值（颜色深度）：

Y为浅色系，则字体颜色为黑色；Y为深色系，则字体颜色为白色

@15521054523
