### ISSUE TITLE
[Enhancement] 期待文章字体和目录优化。。

### ISSUE THREAD

**Issue by Ennn** [Sariay/hexo-theme-Annie#32]
**Describe the solution you'd like**
很不错的主题，就是目录和字体总是有种老人机的既视感(look so big)。。sorry fo that
看到TODO里有这个计划，希望可以快点实现。
thx~

**Comment by Sariay** [comment]
好的呢，重构主题中！最晚月底放出 @Ennn

**Comment by Sariay** [comment]
好的呢！最晚月底放出 @Ennn

**Comment by Sariay** [comment]
好的呢！最晚月底放出 @Ennn

**Comment by Ennn** [comment]
谢谢！厉害👍
