### ISSUE TITLE
[Bug] 移动端窗口抖动

### ISSUE THREAD

**Issue by Asalea** [Sariay/hexo-theme-Annie#33]
移动端网页加载完毕后，滑动窗口式仍然存在激烈的抖动。

同时移动端背景图片显示不全，建议移动端可以略去背景。

**Comment by Sariay** [comment]
晚好！@Asalea 

最近比较忙，窗口抖动问题以后会修复！

至于移动端略去背景确实是一个不错的建议。

**Comment by purer01** [comment]
首页在移动端的显示不同于PC端
