### ISSUE TITLE
[Question]：背景图片加载失败

### ISSUE THREAD

**Issue by Asalea** [Sariay/hexo-theme-Annie#35]
Hi,Sariay,周末好
最近我尝试使用又拍云代替github作为图床，但是遇到了一些问题。

首页的封面图和文章内部的图片外链都可以正常加载，可是文章页面的背景图片每次都会加载失败。网路上似乎没有见到类似问题，我对前端知识了解的又很少，希望你能给出一些解决的思路或办法。

这是我的博客链接：
https://asalea.github.io/

**Comment by Sariay** [comment]
下午好！@Asalea 

首先，你应该阅读一下又拍云文档的[CORS跨域配置](https://docs.upyun.com/cdn/feature/#cors)一节；然后转到**管理后台**，找到**云储存**，找到**管理图片的服务**，点击**配置**，配置**访问控制**模块的**CORS 跨域共享** ，点击**添加规则**，配置允许的域为 *，Method至少选择post和get两项。

更多问题请谷歌**跨域访问**一词。

**Comment by Asalea** [comment]
感谢帮助，问题已解决。

主要问题是又拍云对于跨域的请求不会默认添加Access-Control-Allow-Origin，我尝试了添加各种CORS规则，但是没有效果。

现在采用一种暂时的方法：**关闭CORS规则并添加重写规则。**

步骤大致这样：管理后台 -> 云存储 -> 找到服务 -> 配置  -> 边缘规则 -> 添加规则 -> 功能选择添加HTTP响应头，Header域名为**Access-Control-Allow-Origin** ， Header域值设置为  '\*'  -> 选择break
