### ISSUE TITLE
[Question]：单行代码块首字母自动大写

### ISSUE THREAD

**Issue by DiDongDongDi** [Sariay/hexo-theme-Annie#36]
您好, `abc`代码块首字母会自动大写为`Abc`, 请问怎么解决啊?
还有标题所有字母也会自动大写

**Comment by Sariay** [comment]
目前似乎不存在这种问题。

代码块标题字母默认全大写


你可以给一个网页链接，我看一下！ @DiDongDongDi

**Comment by DiDongDongDi** [comment]
https://wangqy.cc/2019/05/06/vimscript%E7%AC%94%E8%AE%B0%E2%80%94%E2%80%940%E2%80%94%E2%80%94%E5%8D%95%E8%A1%8C%E5%91%BD%E4%BB%A4/

**Comment by Sariay** [comment]
- 例子：:Echo "Hello, world!，信息不会保存。Echo 中E大写了！

- 原因：主题中p段落的首字母默认大写

-  解决：注释掉此段代码https://github.com/Sariay/hexo-theme-Annie/blob/972f113acdbdba818c9dfd5c52b4c1ec8b30f691/source/css/_main.styl#L140

@DiDongDongDi

**Comment by DiDongDongDi** [comment]
已解决, 谢谢! @Sariay
