### ISSUE TITLE
Hexo generate error

### ISSUE THREAD

**Issue by Fiona2013** [Sariay/hexo-theme-Annie#4]
When git clone total repo to the themes file at my localhost, and execute hexo generate and hexo server it will show the issue as below.

`Cannot read property 'path' of undefined
TypeError: /Users/niyao/N.Y./Projects/FrontEnd/Fiona2013BlogRepo/themes/Annie/layout/layout.ejs:22
    20| 		</main>
    21| 
 >> 22| 		<%- partial('_partial/footer-after') %>
    23| 	</body>
    24| 	</html>
    25| 
`

How can I solve it?

**Comment by Fiona2013** [comment]
Total Error
```
ERROR /Users/niyao/N.Y./Projects/FrontEnd/Fiona2013BlogRepo/themes/Annie/layout/layout.ejs:22
    20| 		</main>
    21| 
 >> 22| 		<%- partial('_partial/footer-after') %>
    23| 	</body>
    24| 	</html>
    25| 

/Users/niyao/N.Y./Projects/FrontEnd/Fiona2013BlogRepo/themes/Annie/layout/_partial/footer-after.ejs:12
    10| 
    11| <% if (theme.local_search.enable) { %>
 >> 12|     <%- partial('_partial/third/search') %>
    13| <% } %>
    14| 
    15| <% if (theme.love.enable) { %>

/Users/niyao/N.Y./Projects/FrontEnd/Fiona2013BlogRepo/themes/Annie/layout/_partial/third/search.ejs:29
    27|     var isXml = true;
    28|     // Search DB path;
 >> 29|     var search_path = "<%= config.search.path %>";
    30|     if (search_path.length === 0) {
    31|       search_path = "search.xml";
    32|     } else if (/json$/i.test(search_path)) {

Cannot read property 'path' of undefined
```

**Comment by Fiona2013** [comment]
@Sariay I set the _config.yml as follow
```
# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: false
```
So that, it will not exist the ERROR. However, it is not the best way to the problem. Can you help me?

**Comment by Sariay** [comment]
oh! you can see the issue [issue1](https://github.com/Sariay/hexo-theme-Annie/issues/1#issue-355000746)

it can help you.

@Fiona2013

**Comment by Fiona2013** [comment]
@Sariay Thanks.
