### ISSUE TITLE
首页滑动问题

### ISSUE THREAD

**Issue by KongYisong** [Sariay/hexo-theme-Annie#43]
在 Mac 端 （MacBook Pro 15 寸）下，进入网站首页后，由首页图片向下滑动时，出现卡顿现象，给人的感觉就像『阻尼』很大一样。Safari 浏览器 和 Chrome 浏览器都有这个问题。

**Comment by BLinyun** [comment]
不知道与我遇到的是不是同一个问题：手机端访问（不仅仅是首页）往下滑动时页面会抖动（卡顿的），Safari 浏览器 和 Chrome 浏览器都有这个问题
