### ISSUE TITLE
[集成DaoVoice] 可否给此主题集成DaoVoice

### ISSUE THREAD

**Issue by 10veU** [Sariay/hexo-theme-Annie#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sariay** [comment]
谷歌有很多教程，很简单！！！

关键字：hexo添加[DaoVoice](http://www.aomanhao.top/2019/05/18/Hexo_Daovoice/)

@10veU
