### ISSUE TITLE
相册功能的使用、搜索功能

### ISSUE THREAD

**Issue by SeniorBrother** [Sariay/hexo-theme-Annie#5]
1. 相册目前文档没有介绍使用，网上的也是层出不穷，花样百出，这个相册如何使用，能否做个说明完善下
2. 搜索功能 下载的安装 search.zip 必须上传到 git 吗？每次 hexo d 感觉有点慢卡顿

**Comment by Sariay** [comment]
午好！

1. 你不妨等更新完毕后，按照文章[《Annie主题使用说明》](https://sariay.github.io/2018/08/27/Annie主题使用说明/)配置即可！

2. zip目前是最小的包，慢卡顿可能是因为本地图片太多或其他原因。

   zip包相当于数据库，没有数据库无法搜索数据。

@SeniorBrother
