### ISSUE TITLE
[Question]: 打开文章详情页，右上角的大图标点赞在哪控制，我的为什么不显示？

### ISSUE THREAD

**Issue by 10veU** [Sariay/hexo-theme-Annie#55]
**为避免无效问题和冗余问题，提问前请确认**
- [ ] 你确定Google不能解决你的问题
- [ ] 你确定已有的issue不能解决你的问题
- [ ] 你确定issue的title按照格式如下：[type]：description

**Comment by Sariay** [comment]
你好，以前的版本直接点击标题下面的“心形图标”。

目前还未更新主题！

@10veU
