### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by zxdawn** [Sariay/hexo-theme-Annie#6]
Thank you for your good work! It's beautiful and clean :-)

**Here're some suggestions:**

1. Cover
    Let the content lay over the cover when scrolling down, like [this](https://davidtoppingsci.com/).
2. Fonts in cover
    The black font isn't clear when the cover is dark.
3. Footer
    Add busuanzi in the footer.
4. Language
    Is it possible to develop an English version and we can switch between English and Chinese?
5. Gallery
   Is it possible to use different photos in gallery as covers of different article and thumbnail?
6. Mobile version
    It's better to enlarge the side boundary.
7. Comment
I found an awesome [commentbox](https://commentbox.io/) and you can try it.

Hope this can help you develop it. Thanks!

**Comment by Sariay** [comment]
Good ideas, thanks!

@zxdawn

**Comment by iDestin** [comment]
logo加载不出来怎么办？？？

**Comment by Simeng07** [comment]
https://sariay.github.io/ 里面的好好看，什么时候更新模板呀期待！

**Comment by Sariay** [comment]
@SMartQi 

主题已更新，如你仍使用Annie！

**Comment by Lansm** [comment]
刚开始学习github和博客，主题很喜欢，加油咯

**Comment by Lansm** [comment]
问一下 博主的切换背景怎么用不了=-=

**Comment by Sariay** [comment]
额，这个小功能没有实现呢！ @Lansm

**Comment by origingx** [comment]
能不能转换一下ghost的这个主题。https://demo.ghost.io/？

**Comment by origingx** [comment]
主页背景图上的字体能否更换？感觉宋体不好看。
主页背景图上的文字颜色，能否根据背景亮度更换，现在白色为主的背景，上面显示白色字看不清
每篇文章的配图，是按照什么比例缩放的，我自己的图片不是指定的比例就会出现不按比例拉伸吧
你的搜索功能下面显示一大块白颜色的区域。这个不太好。
每篇文章之间文字和图片的排版是否可以再做的排版方式多一些，比如像ghost的这个主题https://demo.ghost.io/。

**Comment by Sariay** [comment]
@origingx 

- 关于定制问题：请自己完成

- 关于设计与排版：后面学习后，再重构

**Comment by Ian-peace** [comment]
网页加载速度有些太慢了，请问我应该怎么优化？

**Comment by Sariay** [comment]
> 网页加载速度有些太慢了，请问我应该怎么优化？

 @Ian-peace， 晚好：

第一点：更换主机；

第二点：更换图床；

第三点：压缩站点资源。

more......（网上搜具体教程）

**Comment by zxdawn** [comment]
@Sariay 请问图床有什么推荐的嘛？github国内加载太慢;自己搭在服务器上，换了IP，又得更改。

**Comment by Sariay** [comment]
七牛，腾讯云，阿里云。原则上提供“对象储存”服务则可以！

@zxdawn

**Comment by Ian-peace** [comment]
请问在社交链接处怎么增加哔哩哔哩图标，我不清楚图标怎么加上去。icon: fa fa-bilibili 并没有图标显示

**Comment by Ian-peace** [comment]
是要修改favicon.ico文件吗？怎么修改啊？我打不开这个文件

**Comment by Ian-peace** [comment]
还有就是，我修改文件的时候输入中文，页面显示的都是乱码，请问我应该怎么修改
