### ISSUE TITLE
[Question]：Gitalk电脑端无法点击评论，不知是插件问题还是主题问题？

### ISSUE THREAD

**Issue by Palpitation-github** [Sariay/hexo-theme-Annie#63]
**为避免无效问题和冗余问题，提问前请确认**
- [ ] 你确定Google不能解决你的问题
- [ ] 你确定已有的issue不能解决你的问题
- [ ] 你确定issue的title按照格式如下：[type]：description
![image](https://user-images.githubusercontent.com/32128684/68306584-c8d27280-00e4-11ea-87cf-d926f8e7efef.png)
如图所示，gitalk正常设置，但是在电脑端无法点击评论进行评论，包括预览也是不可以的，但是在移动端可以，希望大佬可以指导一下，蟹蟹

**Comment by Sariay** [comment]
插件问题，preact. js是GITALK使用文件 @voidmaker69
