### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by mxdlsm** [Sariay/hexo-theme-Annie#8]
您好，谢谢您，上一个问题解决了。可是我在主题下的配置文件里配置
index_generator:
  path: ''
  per_page: 3
  order_by: -date
为什么还是不显示加载更多，一次性都加载出来了。
还有发文章左侧的图片怎么修改？每次都是固定的图片。

**Comment by Sariay** [comment]
**关于首页分页问题：**

确保你上述所说得的参数格式正确，再将per_page置为0试试

**关于文章封面图问题：**

请参考主题仓库的read.md的最后部分

@BaiMingxu
