### ISSUE TITLE
menu里怎么没有词句？

### ISSUE THREAD

**Issue by mxdlsm** [Sariay/hexo-theme-Annie#9]
有词句的文档么？

**Comment by mxdlsm** [comment]
为什么评论用不了？一直这样，不是集成好了么？
<img width="585" alt="_20181030211951" src="https://user-images.githubusercontent.com/22886455/47720880-e1b27780-dc89-11e8-99b5-ffbeb7fd7ede.png">

**Comment by Sariay** [comment]
关于“词句”页面，暂未更新主题！

关于“评论”功能，请认真阅读使用说明！

@BaiMingxu
